# Generated by Django 5.0.2 on 2024-03-12 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('creation_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('last_updated_by', models.CharField(max_length=50)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('creation_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('last_updated_by', models.CharField(max_length=50)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email_id', models.CharField(max_length=50)),
                ('phone_no', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expencemanagement.group')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expencemanagement.users')),
            ],
        ),
        migrations.CreateModel(
            name='UserExpenceEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expencemanagement.group')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expencemanagement.users')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenceEntry',
            fields=[
                ('creation_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('last_updated_by', models.CharField(max_length=50)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('exp_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('gid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expencemanagement.group')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expencemanagement.users')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
